### ISSUE TITLE
Unified deployment no longer runs because of missing .NET 

### ISSUE THREAD

**Issue by kociubin** [bitwarden/server#3755]
### Steps To Reproduce

1) I started with a working unified docker deployment 
2) Upgraded to the latest 'beta' image (published 43 minutes ago)
3) App no longer starts

4) Downgraded the app to tag: "2024.1.2-beta" (pushed 12 days ago).  Everything works fine with the older image. 

### Expected Result

Expected the app to run normally after upgrading

### Actual Result

App fails to start. 

### Additional Context

bitwarden          | Not creating home directory `/home/bitwarden'.
bitwarden          | Adding new user `bitwarden' to supplemental / extra groups `users' ...
bitwarden          | Adding user `bitwarden' to group `users' ...
bitwarden          | You must install or update .NET to run this application.
bitwarden          |
bitwarden          | App: /usr/local/bin/hbs
bitwarden          | Architecture: x64
bitwarden          | Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
bitwarden          | .NET location: /usr/share/dotnet
bitwarden          |
bitwarden          | The following frameworks were found:
bitwarden          |   8.0.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
bitwarden          |
bitwarden          | Learn more:
bitwarden          | https://aka.ms/dotnet/app-launch-failed
bitwarden          |
bitwarden          | To install missing framework, download:
bitwarden          | https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=linux-x64&os=debian.12
bitwarden          | 2024-02-06 14:18:16,028 INFO Included extra file "/etc/supervisor.d/admin.ini" during parsing
bitwarden          | 2024-02-06 14:18:16,028 INFO Included extra file "/etc/supervisor.d/api.ini" during parsing
bitwarden          | 2024-02-06 14:18:16,028 INFO Included extra file "/etc/supervisor.d/events.ini" during parsing
bitwarden          | 2024-02-06 14:18:16,028 INFO Included extra file "/etc/supervisor.d/icons.ini" during parsing
bitwarden          | 2024-02-06 14:18:16,028 INFO Included extra file "/etc/supervisor.d/identity.ini" during parsing
bitwarden          | 2024-02-06 14:18:16,028 INFO Included extra file "/etc/supervisor.d/nginx.ini" during parsing
bitwarden          | 2024-02-06 14:18:16,028 INFO Included extra file "/etc/supervisor.d/notifications.ini" during parsing
bitwarden          | 2024-02-06 14:18:16,028 INFO Included extra file "/etc/supervisor.d/scim.ini" during parsing
bitwarden          | 2024-02-06 14:18:16,028 INFO Included extra file "/etc/supervisor.d/sso.ini" during parsing
bitwarden          | 2024-02-06 14:18:16,035 INFO RPC interface 'supervisor' initialized
bitwarden          | 2024-02-06 14:18:16,035 CRIT Server 'unix_http_server' running without any HTTP authentication checking
bitwarden          | 2024-02-06 14:18:16,035 INFO supervisord started with pid 1
bitwarden          | 2024-02-06 14:18:17,038 INFO spawned: 'identity' with pid 55
bitwarden          | 2024-02-06 14:18:17,040 INFO spawned: 'admin' with pid 56
bitwarden          | 2024-02-06 14:18:17,042 INFO spawned: 'api' with pid 57
bitwarden          | 2024-02-06 14:18:17,044 INFO spawned: 'icons' with pid 58
bitwarden          | 2024-02-06 14:18:17,045 INFO spawned: 'nginx' with pid 59
bitwarden          | 2024-02-06 14:18:17,048 INFO spawned: 'notifications' with pid 61
bitwarden          | 2024-02-06 14:18:17,049 WARN exited: identity (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:17,050 WARN exited: admin (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:17,050 WARN exited: api (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:17,055 WARN exited: icons (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:17,058 WARN exited: notifications (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:17,065 WARN exited: nginx (exit status 1; not expected)
bitwarden          | 2024-02-06 14:18:18,067 INFO spawned: 'identity' with pid 62
bitwarden          | 2024-02-06 14:18:18,069 INFO spawned: 'admin' with pid 63
bitwarden          | 2024-02-06 14:18:18,071 INFO spawned: 'api' with pid 64
bitwarden          | 2024-02-06 14:18:18,073 INFO spawned: 'icons' with pid 65
bitwarden          | 2024-02-06 14:18:18,075 INFO spawned: 'nginx' with pid 66
bitwarden          | 2024-02-06 14:18:18,077 INFO spawned: 'notifications' with pid 67
bitwarden          | 2024-02-06 14:18:18,077 WARN exited: identity (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:18,078 WARN exited: admin (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:18,081 WARN exited: api (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:18,084 WARN exited: notifications (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:18,089 WARN exited: icons (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:18,093 WARN exited: nginx (exit status 1; not expected)
bitwarden          | 2024-02-06 14:18:20,096 INFO spawned: 'identity' with pid 68
bitwarden          | 2024-02-06 14:18:20,098 INFO spawned: 'admin' with pid 69
bitwarden          | 2024-02-06 14:18:20,100 INFO spawned: 'api' with pid 70
bitwarden          | 2024-02-06 14:18:20,103 INFO spawned: 'icons' with pid 71
bitwarden          | 2024-02-06 14:18:20,106 INFO spawned: 'nginx' with pid 72
bitwarden          | 2024-02-06 14:18:20,108 INFO spawned: 'notifications' with pid 73
bitwarden          | 2024-02-06 14:18:20,109 WARN exited: admin (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:20,110 WARN exited: identity (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:20,121 WARN exited: api (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:20,123 WARN exited: notifications (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:20,124 WARN exited: icons (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:20,124 WARN exited: nginx (exit status 1; not expected)
bitwarden          | 2024-02-06 14:18:23,128 INFO spawned: 'identity' with pid 74
bitwarden          | 2024-02-06 14:18:23,130 INFO spawned: 'admin' with pid 75
bitwarden          | 2024-02-06 14:18:23,132 INFO spawned: 'api' with pid 76
bitwarden          | 2024-02-06 14:18:23,133 INFO spawned: 'icons' with pid 77
bitwarden          | 2024-02-06 14:18:23,136 INFO spawned: 'nginx' with pid 78
bitwarden          | 2024-02-06 14:18:23,138 INFO spawned: 'notifications' with pid 79
bitwarden          | 2024-02-06 14:18:23,139 WARN exited: admin (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:23,139 INFO gave up: admin entered FATAL state, too many start retries too quickly
bitwarden          | 2024-02-06 14:18:23,140 WARN exited: identity (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:23,142 INFO gave up: identity entered FATAL state, too many start retries too quickly
bitwarden          | 2024-02-06 14:18:23,142 WARN exited: api (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:23,143 INFO gave up: api entered FATAL state, too many start retries too quickly
bitwarden          | 2024-02-06 14:18:23,146 WARN exited: icons (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:23,147 INFO gave up: icons entered FATAL state, too many start retries too quickly
bitwarden          | 2024-02-06 14:18:23,150 WARN exited: notifications (exit status 150; not expected)
bitwarden          | 2024-02-06 14:18:23,150 WARN exited: nginx (exit status 1; not expected)
bitwarden          | 2024-02-06 14:18:23,150 INFO gave up: nginx entered FATAL state, too many start retries too quickly
bitwarden          | 2024-02-06 14:18:23,151 INFO gave up: notifications entered FATAL state, too many start retries too quickly

### Githash Version

na

### Environment Details

Docker

### Database Image

MariaDB

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by seanob86** [comment]
I too got the same errors and also rolled back "2024.1.2-beta". Using sqlite db.

**Comment by MichaelSch** [comment]
Confirmed. A rollback solved the issue for me as well.

**Comment by adamaen87** [comment]
Same problem here, rolled back to 2024.1.2

**Comment by cbbit** [comment]
@kociubin 

Hi there,

Thank you for your report! 

This issue has been flagged this to our engineering team for further investigation.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by dtashlykov** [comment]
Same problem here as well, only started with the latest version.

Rolling back to the `bitwarden/self-host:2024.1.2-beta` image works great; dotnet error mentioning .NET Framework 6.0, even though I have the latest framework(s) on my server (and even made sure to install the 6.0 SDK), which didn't solve the issue.

**Comment by Duke-Igthorn** [comment]
Same here. Rolled back and all is okay for now. After my MariaDB crashed and burned a few weeks back and I re-setup everything with SQLite I was a bit afraid I broke something. Kinda relieved it's an outside problem. 😅

**Comment by 7djs7** [comment]
Having the same error. Using MariaDB. Going to try and roll back to 204.1.2-beta.

**Comment by Akitash** [comment]
same issue with postgre 14. The rollback solves the issue

**Comment by bigwookie** [comment]
I also noticed this in the nginx.log

2024/02/08 14:44:39 [emerg] 60#60: open() "/etc/nginx/http.d/bitwarden.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:37
2024/02/08 14:44:40 [emerg] 112#112: open() "/etc/nginx/http.d/bitwarden.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:37
2024/02/08 14:44:43 [emerg] 119#119: open() "/etc/nginx/http.d/bitwarden.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:37
2024/02/08 14:44:46 [emerg] 146#146: open() "/etc/nginx/http.d/bitwarden.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:37

**Comment by holow29** [comment]
Unfortunately still seems to be an issue with the now-versioned [2024.2.0-beta](https://hub.docker.com/layers/bitwarden/self-host/2024.2.0-beta/images/sha256-b95e674e31dae438df0a1e4767b9c6fffe4dd8f945d48c605922f9e4c4785fbc?context=explore)

**Comment by bigwookie** [comment]
Yes still have the same isue.

**Comment by boerge30** [comment]
Tried again with the last beta... same error.

```
You must install or update .NET to run this application.
App: /usr/local/bin/hbs
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (arm64)
.NET location: /usr/share/dotnet
The following frameworks were found:
  8.0.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Learn more:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=arm64&rid=linux-arm64&os=debian.12
2024-02-09 05:19:17,702 INFO Included extra file "/etc/supervisor.d/admin.ini" during parsing
2024-02-09 05:19:17,702 INFO Included extra file "/etc/supervisor.d/api.ini" during parsing
2024-02-09 05:19:17,703 INFO Included extra file "/etc/supervisor.d/events.ini" during parsing
2024-02-09 05:19:17,703 INFO Included extra file "/etc/supervisor.d/icons.ini" during parsing
2024-02-09 05:19:17,703 INFO Included extra file "/etc/supervisor.d/identity.ini" during parsing
2024-02-09 05:19:17,703 INFO Included extra file "/etc/supervisor.d/nginx.ini" during parsing
2024-02-09 05:19:17,703 INFO Included extra file "/etc/supervisor.d/notifications.ini" during parsing
2024-02-09 05:19:17,703 INFO Included extra file "/etc/supervisor.d/scim.ini" during parsing
2024-02-09 05:19:17,703 INFO Included extra file "/etc/supervisor.d/sso.ini" during parsing
2024-02-09 05:19:17,721 INFO RPC interface 'supervisor' initialized
2024-02-09 05:19:17,722 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-02-09 05:19:17,723 INFO supervisord started with pid 1
2024-02-09 05:19:18,727 INFO spawned: 'identity' with pid 55
2024-02-09 05:19:18,732 INFO spawned: 'admin' with pid 56
2024-02-09 05:19:18,738 INFO spawned: 'api' with pid 57
2024-02-09 05:19:18,744 INFO spawned: 'icons' with pid 58
2024-02-09 05:19:18,750 INFO spawned: 'nginx' with pid 59
2024-02-09 05:19:18,757 INFO spawned: 'notifications' with pid 60
2024-02-09 05:19:18,759 WARN exited: identity (exit status 150; not expected)
2024-02-09 05:19:18,762 WARN exited: admin (exit status 150; not expected)
2024-02-09 05:19:18,763 WARN exited: api (exit status 150; not expected)
2024-02-09 05:19:18,772 WARN exited: icons (exit status 150; not expected)
2024-02-09 05:19:18,777 WARN exited: notifications (exit status 150; not expected)
2024-02-09 05:19:18,792 WARN exited: nginx (exit status 1; not expected)
2024-02-09 05:19:19,797 INFO spawned: 'identity' with pid 61
2024-02-09 05:19:19,803 INFO spawned: 'admin' with pid 62
2024-02-09 05:19:19,807 INFO spawned: 'api' with pid 63
2024-02-09 05:19:19,813 INFO spawned: 'icons' with pid 64
2024-02-09 05:19:19,819 INFO spawned: 'nginx' with pid 65
2024-02-09 05:19:19,826 INFO spawned: 'notifications' with pid 66
2024-02-09 05:19:19,828 WARN exited: identity (exit status 150; not expected)
2024-02-09 05:19:19,829 WARN exited: admin (exit status 150; not expected)
2024-02-09 05:19:19,834 WARN exited: api (exit status 150; not expected)
2024-02-09 05:19:19,842 WARN exited: icons (exit status 150; not expected)
2024-02-09 05:19:19,851 WARN exited: nginx (exit status 1; not expected)
2024-02-09 05:19:19,855 WARN exited: notifications (exit status 150; not expected)
2024-02-09 05:19:21,860 INFO spawned: 'identity' with pid 67
2024-02-09 05:19:21,865 INFO spawned: 'admin' with pid 68
2024-02-09 05:19:21,870 INFO spawned: 'api' with pid 69
2024-02-09 05:19:21,875 INFO spawned: 'icons' with pid 70
2024-02-09 05:19:21,881 INFO spawned: 'nginx' with pid 71
2024-02-09 05:19:21,890 INFO spawned: 'notifications' with pid 72
2024-02-09 05:19:21,891 WARN exited: identity (exit status 150; not expected)
2024-02-09 05:19:21,892 WARN exited: admin (exit status 150; not expected)
2024-02-09 05:19:21,897 WARN exited: api (exit status 150; not expected)
2024-02-09 05:19:21,908 WARN exited: notifications (exit status 150; not expected)
2024-02-09 05:19:21,911 WARN exited: icons (exit status 150; not expected)
2024-02-09 05:19:21,913 WARN exited: nginx (exit status 1; not expected)
2024-02-09 05:19:24,923 INFO spawned: 'identity' with pid 73
2024-02-09 05:19:24,932 INFO spawned: 'admin' with pid 74
2024-02-09 05:19:24,941 INFO spawned: 'api' with pid 75
2024-02-09 05:19:24,951 INFO spawned: 'icons' with pid 76
2024-02-09 05:19:24,960 INFO spawned: 'nginx' with pid 77
2024-02-09 05:19:24,985 INFO spawned: 'notifications' with pid 78
2024-02-09 05:19:24,988 WARN exited: identity (exit status 150; not expected)
2024-02-09 05:19:24,999 WARN exited: admin (exit status 150; not expected)
2024-02-09 05:19:25,000 WARN exited: api (exit status 150; not expected)
2024-02-09 05:19:25,015 INFO gave up: identity entered FATAL state, too many start retries too quickly
2024-02-09 05:19:25,016 INFO gave up: admin entered FATAL state, too many start retries too quickly
2024-02-09 05:19:25,017 INFO gave up: api entered FATAL state, too many start retries too quickly
2024-02-09 05:19:25,017 WARN exited: icons (exit status 150; not expected)
2024-02-09 05:19:25,018 INFO gave up: icons entered FATAL state, too many start retries too quickly
2024-02-09 05:19:25,019 WARN exited: notifications (exit status 150; not expected)
2024-02-09 05:19:25,019 INFO gave up: notifications entered FATAL state, too many start retries too quickly
2024-02-09 05:19:25,027 WARN exited: nginx (exit status 1; not expected)
2024-02-09 05:19:26,028 INFO gave up: nginx entered FATAL state, too many start retries too quickly
```

**Comment by shofutex** [comment]
I can confirm this error as well upgrading to 2024.2.0-beta:

bitwarden_1  | Adding user `bitwarden' to group `users' ...
db_1         | 2024-02-10 23:36:14 0 [Note] InnoDB: Buffer pool(s) load completed at 240210 23:36:14
db_1         | 2024-02-10 23:36:14 0 [Note] mariadbd: ready for connections.
db_1         | Version: '10.11.6-MariaDB-1:10.11.6+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
bitwarden_1  | You must install or update .NET to run this application.
bitwarden_1  | 
bitwarden_1  | App: /usr/local/bin/hbs
bitwarden_1  | Architecture: x64
bitwarden_1  | Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
bitwarden_1  | .NET location: /usr/share/dotnet
bitwarden_1  | 
bitwarden_1  | The following frameworks were found:
bitwarden_1  |   8.0.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
bitwarden_1  | 
bitwarden_1  | Learn more:
bitwarden_1  | https://aka.ms/dotnet/app-launch-failed
bitwarden_1  | 
bitwarden_1  | To install missing framework, download:
bitwarden_1  | https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=linux-x64&os=debian.12

**Comment by shofutex** [comment]
It looks like the image is downloading https://github.com/bitwarden/Handlebars.conf/releases/download/v1.3.0/hbs_linux-x64_dotnet.zip

When I download that file, it says it needs .NET 6.
You must install .NET to run this application.

App: /home/shofutex/hbs/hbs
Architecture: x64
App host version: 6.0.10
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.22.04-x64&apphost_version=6.0.10

**Comment by stevefan1999-personal** [comment]
A lot of the dependencies are still using 6.0 references. It is better to work around it by installing dotnet 6.0 SDK on unified setup as well. This will significantly increase the image size, but it will get the problem solved in the mid-term until we sorted out all the outdated references.

**Comment by jcbvm** [comment]
Why does it take so long to fix this? Just add .net 6 to the image, even if it is temporary. Can this get some more prio please

**Comment by mind12** [comment]
There is a new beta just released and still  no joy :/

**Comment by 7djs7** [comment]
> A lot of the dependencies are still using 6.0 references. It is better to work around it by installing dotnet 6.0 SDK on unified setup as well. This will significantly increase the image size, but it will get the problem solved in the mid-term until we sorted out all the outdated references.
> 
> ```dockerfile
> FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS legacy-aspnet-6.0
> FROM mcr.microsoft.com/dotnet/runtime:6.0 AS legacy-runtime-6.0
> FROM bitwarden/self-host:beta
> COPY --from=legacy-aspnet-6.0 ["/usr/share/dotnet/shared/", "/usr/share/dotnet/shared/"]
> COPY --from=legacy-runtime-6.0 ["/usr/share/dotnet/shared/", "/usr/share/dotnet/shared/"]
> COPY --from=legacy-runtime-6.0 ["/usr/share/dotnet/host/", "/usr/share/dotnet/host/"]
> ```

What are the exact steps to make a new image based on this method?

**Comment by stevefan1999-personal** [comment]
> > A lot of the dependencies are still using 6.0 references. It is better to work around it by installing dotnet 6.0 SDK on unified setup as well. This will significantly increase the image size, but it will get the problem solved in the mid-term until we sorted out all the outdated references.
> > ```dockerfile
> > FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS legacy-aspnet-6.0
> > FROM mcr.microsoft.com/dotnet/runtime:6.0 AS legacy-runtime-6.0
> > FROM bitwarden/self-host:beta
> > COPY --from=legacy-aspnet-6.0 ["/usr/share/dotnet/shared/", "/usr/share/dotnet/shared/"]
> > COPY --from=legacy-runtime-6.0 ["/usr/share/dotnet/shared/", "/usr/share/dotnet/shared/"]
> > COPY --from=legacy-runtime-6.0 ["/usr/share/dotnet/host/", "/usr/share/dotnet/host/"]
> > ```
> 
> What are the exact steps to make a new image based on this method?

Just put that into a Dockerfile and `docker build -t your_image`

**Comment by 7djs7** [comment]
> > > A lot of the dependencies are still using 6.0 references. It is better to work around it by installing dotnet 6.0 SDK on unified setup as well. This will significantly increase the image size, but it will get the problem solved in the mid-term until we sorted out all the outdated references.
> > > ```dockerfile
> > > FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS legacy-aspnet-6.0
> > > FROM mcr.microsoft.com/dotnet/runtime:6.0 AS legacy-runtime-6.0
> > > FROM bitwarden/self-host:beta
> > > COPY --from=legacy-aspnet-6.0 ["/usr/share/dotnet/shared/", "/usr/share/dotnet/shared/"]
> > > COPY --from=legacy-runtime-6.0 ["/usr/share/dotnet/shared/", "/usr/share/dotnet/shared/"]
> > > COPY --from=legacy-runtime-6.0 ["/usr/share/dotnet/host/", "/usr/share/dotnet/host/"]
> > > ```
> > 
> > 
> > What are the exact steps to make a new image based on this method?
> 
> Just put that into a Dockerfile and `docker build -t your_image`

I apologize i'm a beginner with vast amounts of docker options and variables. How then do I include this new image into my docker compose for bitwarden unified?  Right now in docker compose i have "image: bitwarden/self-host:beta" under "services" and "bitwarden"

**Comment by 7djs7** [comment]
> > > > A lot of the dependencies are still using 6.0 references. It is better to work around it by installing dotnet 6.0 SDK on unified setup as well. This will significantly increase the image size, but it will get the problem solved in the mid-term until we sorted out all the outdated references.
> > > > ```dockerfile
> > > > FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS legacy-aspnet-6.0
> > > > FROM mcr.microsoft.com/dotnet/runtime:6.0 AS legacy-runtime-6.0
> > > > FROM bitwarden/self-host:beta
> > > > COPY --from=legacy-aspnet-6.0 ["/usr/share/dotnet/shared/", "/usr/share/dotnet/shared/"]
> > > > COPY --from=legacy-runtime-6.0 ["/usr/share/dotnet/shared/", "/usr/share/dotnet/shared/"]
> > > > COPY --from=legacy-runtime-6.0 ["/usr/share/dotnet/host/", "/usr/share/dotnet/host/"]
> > > > ```
> > > 
> > > 
> > > What are the exact steps to make a new image based on this method?
> > 
> > 
> > Just put that into a Dockerfile and `docker build -t your_image`
> 
> I apologize i'm a beginner with vast amounts of docker options and variables. How then do I include this new image into my docker compose for bitwarden unified? Right now in docker compose i have "image: bitwarden/self-host:beta" under "services" and "bitwarden"

I think I figured it out myself.  I made a file called "Dockerfile" with no extension in the same directory as my docker compose file. I then copied and pasted the code from stevefan1999-personal's post into this file. I then ran the command in the same directory "docker build -t bitwarden-modified:beta ." I had to make sure included a "." after "beta" for docker build to use the Dockerfile in the current directory. I then proceeded to edit my docker compose file to "image: bitwarden-modified:beta"  and then start the container with "docker compose up -d" and voila!! It works. 

I am assuming I'll have to rebuild this image manually after every update to bitwarden/self-host:beta on dockerhub.

**Comment by shofutex** [comment]
Latest release (pushed a day ago) has the following error:
bitwarden_1  | /entrypoint.sh: line 85:    41 Aborted                 (core dumped) /usr/local/bin/hbs

**Comment by Noobstradamus** [comment]
Agreed, this has been a system breaking issue for several weeks now and should be higher priority as anyone using unified beta cannot upgrade for security, functionality, or bug fixing purposes. Is it possible for this to be resolved this week?

**Comment by kociubin** [comment]
Agree.  This should be considered a showstopper severity issue.   Surprised it's not fixed yet.

**Comment by shofutex** [comment]
Bitwarden committed an update to their hbs library they use a few days ago to update it for .NET 8. That's what led me to test again. https://github.com/bitwarden/Handlebars.conf/commit/6e2a599aebcacf56cf07907961ffc789084bb0fe

**Comment by shofutex** [comment]
> > Bitwarden committed an update to their hbs library they use a few days ago to update it for .NET 8 and released a new version. That's what led me to test again. [bitwarden/Handlebars.conf@6e2a599](https://github.com/bitwarden/Handlebars.conf/commit/6e2a599aebcacf56cf07907961ffc789084bb0fe)
> 
> 
> 
> I was confused by your comment are you saying that it is working now after you tested or was it still non-functional for you?

It was still non-functional, but this time the error was a core dump rather than an error about .NET versions.

**Comment by shofutex** [comment]
Just tried the latest push (3 hours ago). Still getting this error:
`bitwarden_1  | /entrypoint.sh: line 85:    41 Aborted                 (core dumped) /usr/local/bin/hbs`

**Comment by holow29** [comment]
As others have mentioned, this specific issue was resolved, but now the issue is https://github.com/bitwarden/server/issues/3820

**Comment by Noobstradamus** [comment]
Changing from beta to dev has resolved it for me and everything is working at the moment.

**Comment by GitTimeraider** [comment]
> 2024.1.2-beta

Hmm, really hoping they port over the changes from dev to beta then. For the beta tag the .net error has disappeared but now has nginx user issues -_-

**Comment by Noobstradamus** [comment]
@GitTimeraider Can you elaborate on those nginx user issues you are seeing or link to an existing issue? I am not seeing any problems so just want to see if I can reproduce.

**Comment by GitTimeraider** [comment]
@Noobstradamus  .. basically this. When using the latest beta version (not dev) below happens at me as well. Before U had the .net issue but now I keep having the issue whereby the nginx user started by the container just keeps crashing untill a fatal error.
And this makes it so that its still not usable

> As others have mentioned, this specific issue was resolved, but now the issue is #3820

**Comment by kociubin** [comment]
I just tried the latest "beta" (pushed on Feb 26, 2024 at 1:11 pm).

Issue is still not resolved.

**Comment by GitTimeraider** [comment]
> I just tried the latest "beta" (pushed on Feb 26, 2024 at 1:11 pm).
> 
> Issue is still not resolved.

Weird, latest beta works perfectly fine for me. Neither .net nor nginx errors

**Comment by shofutex** [comment]
Latest beta works for me as well.

**Comment by kociubin** [comment]
Latest beta works now.

**Comment by kociubin** [comment]
> > I just tried the latest "beta" (pushed on Feb 26, 2024 at 1:11 pm).
> > Issue is still not resolved.
> 
> Weird, latest beta works perfectly fine for me. Neither .net nor nginx errors

I agree.  I must have done something wrong.  It works now.

**Comment by Duke-Igthorn** [comment]
Yeah, just reverted back to latest beta and all is working. 👍

**Comment by Nicolaj-H** [comment]
i can confirm that latest :beta works here also.

**Comment by stevefan1999-personal** [comment]
Also tried the latest beta on my fly.io instance :) Worked like a charm

**Comment by djsmith85** [comment]
Thanks everyone for your patience and the reports of this being fixed.

Closing this now.
